Add new plugin type for custom schema validators
asdf-format/asdf pull request #1050
Opened 2022-01-18 23:55 UTC by eslavich

This adds a new plugin type for custom schema validators.  We need this in order to implement support for ndarray using the Converter API.

2022-01-18 23:57 UTC, eslavich commented
@CagtayFabry will this work for your use case?  The URI patterns seem to nicely resolve the issues we were discussing around the scope of the custom validator.

2022-01-19 09:51 UTC, CagtayFabry commented
thank you for starting this @eslavich 

I will have to take a closer look but from a quick scan it looks good to me.
Regarding URI pattern association: in the example listed if I wanted to 'enable' (associate?) the `MaxAreaValidator` for all schemas listed unter `/tags/` I would do this?
```python
from asdf.extension import Validator
from asdf.exceptions import ValidationError

class MaxAreaValidator(Validator):
    schema_property = "max_area"
    tags = ["asdf://example.com/example-project/tags/**"]
```

2022-01-19 13:55 UTC, eslavich commented
> Regarding URI pattern association: in the example listed if I wanted to 'enable' (associate?) the MaxAreaValidator for all schemas listed unter /tags/ I would do this?

Yes, that's right!

2022-01-19 15:13 UTC, CagtayFabry commented
Great, with careful versioning syntax this should also effectively enable versioning of the validators :+1:

I'm quite busy these days but I will try a quick demo implementation with our weldx validators in the next 2 weeks to give feedback, would that work @eslavich ?

2022-01-19 15:22 UTC, eslavich commented
> I'm quite busy these days but I will try a quick demo implementation with our weldx validators in the next 2 weeks to give feedback, would that work @eslavich ?

Yes, that'd be super helpful, thank you!  We might merge this in the meantime, but it's only going into an epic branch and not into master, so there will still be plenty of time to adjust the code based on your feedback.

2022-01-19 15:46 UTC, WilliamJamieson requested changes

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/extension/_extension.py
> +from ._compressor import Compressor
The `Compressor` changes should be moved to a separate PR if possible.

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/extension/_extension.py
> +        iterable of asdf.extension.Compressor
More `Compressor` changes.

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/extension/_extension.py
> +                self._compressors.append(compressor)
More `Compressor` changes.

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/extension/_manifest.py
> +        block compression options.
More `Compressor` changes.

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/tests/test_extension.py
> +    assert subclassed_proxy.compressors == proxy.compressors
More `Compressor` changes.

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/tests/test_extension.py
> +    ]
More `Compressor` changes.

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/tests/test_extension.py
> +        compressors=compressors,
More `Compressor` changes.

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/tests/test_extension.py
> +        compressor = MinimalCompressor()
More `Compressor` changes.

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/tests/test_extension.py
> +            compressors=[compressor],
More `Compressor` changes.

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/tests/test_extension.py
> +        assert extension.compressors == [compressor]
More `Compressor` changes.

2022-01-19 15:46 UTC, WilliamJamieson commented on asdf/tests/test_extension.py
> +        assert proxy.compressors == [compressor]
More `Compressor` changes.

2022-01-31 16:02 UTC, WilliamJamieson approved these changes
Looks good to me.

2022-01-31 17:56 UTC, merged

2022-02-01 23:04 UTC, CagtayFabry commented
a few notes from me @eslavich 

I managed to implement the new API [in a quick draft](https://github.com/BAMWelDX/weldx/compare/master...CagtayFabry:asdf-3.0-validators), so far it seems to work 👍 

One issue that came up where I am not sure if the behavior was actually a a bug in the legacy API:
with the old API the validator would trigger on **any node** in the ASDF tree that had the keyword/validator-property.

Tha also meant that the validator would be in effect for non tagged nodes, here is a simple example from my test cases:

```yaml
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
id: "asdf://weldx.bam.de/weldx/schemas/debug/test_unit_validator-0.1.0"

type: object
properties:
  length_prop:
    description: |
      a simple length quantity with unit validator
    tag: "asdf://weldx.bam.de/weldx/tags/units/quantity-0.1.*"
    wx_unit: "m"

  simple_prop:
    description: simple property without any tag and unit validator
    type: object
    properties:
      value:
        type: number
      units:
        type: string
    wx_units: "kg"
```
Previously the `wx_unit` validator would trigger on both the `length_prop` and the `simple_prop`
Now it only gets triggered on the `length_prop`, when debugging it never enters the `validate` function.

Is this intended? The ability to enable the validator on everything was quite useful.

Do you see any way to also implement this old behavior (I tried not setting anything for `tags` in `Validator` but no luck, I didn't look into your code yet)

On a related note: For some reason the validator gets triggered when the keyword is put on the top level of the schema (instead of next to the individual properties)
```yaml
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
id: "asdf://weldx.bam.de/weldx/schemas/debug/test_unit_validator-0.1.0"

type: object
properties:
  length_prop:
    description: |
      a simple length quantity with unit validator
    tag: "asdf://weldx.bam.de/weldx/tags/units/quantity-0.1.*"
    wx_unit: "m"

  simple_prop:
    description: simple property without any tag and unit validator
    type: object
    properties:
      value:
        type: number
      units:
        type: string
    wx_units: "kg"

wx_unit:
  length_prop: "m"
  simple_prop: "kg"
```
The final `wx_unit` in this gets validated.

2022-02-08 03:14 UTC, eslavich commented
Thanks for the notes @CagtayFabry!

> Is this intended?

Yes, we wanted to support validators scoped to certain tags, so that different developers could share the same validator name without worrying as much about collisions.

> Do you see any way to also implement this old behavior

The wildcard tag pattern `"**"` should match anything, see https://github.com/asdf-format/asdf/blob/asdf-3.0-epic/asdf/extension/_manager.py#L291.  Thinking about this again I was a bit lazy there and should have used built-in tags like `tag:yaml.org,2002:map` for dict, list, etc, so that the tag pattern could select one of those specifically.  I'll make a note to fix that...

> For some reason the validator gets triggered when the keyword is put on the top level of the schema 

That's really strange!  I'll have to look into that one.