Add fsspec http support
asdf-format/asdf pull request #1228
Opened 2022-11-02 13:20 UTC by braingram

Opening an http filesystem file using fsspec returns an object that is incompatible with generic_io. The fsspec object, when treated like a generic_io.RealFile, fails on both the _size and name/uri calculations.

[generic_io.GenericFile._size](https://github.com/asdf-format/asdf/blob/989cd955420ae717dff763c152be3cc21343d244/asdf/generic_io.py#L221) does not appear to be used so this PR removes it from all GenericFile classes.

[fd.name](https://github.com/asdf-format/asdf/blob/989cd955420ae717dff763c152be3cc21343d244/asdf/generic_io.py#L727) is used to calculate the uri (when not otherwise supplied). fsspec http files do not have a name so a different method of defining uri (such as providing one at the time of opening) will need to be used when a uri is necessary. This PR adds a `hasattr` check for name to avoid an exception during creation of the RealFile.

2022-11-02 13:21 UTC, braingram commented
@WilliamJamieson do you know of any uses of generic_io.GenericFile._size? This appears to be calculated for several of the GenericFile subclasses but I'm not seeing a use anywhere in the code.

2022-11-02 13:33 UTC, WilliamJamieson commented
> @WilliamJamieson do you know of any uses of generic_io.GenericFile._size? This appears to be calculated for several of the GenericFile subclasses but I'm not seeing a use anywhere in the code.

No

2022-11-02 21:21 UTC, WilliamJamieson commented
The jwst failure is unrelated and should be fixed by spacetelescope/jwst#7331.

2022-11-02 21:24 UTC, WilliamJamieson requested changes
These changes seem reasonable, do they enable the example in #1146 to work properly now?

If so can you create a test based on that example and add it to `test_asdf.py`?

2022-11-04 17:23 UTC, braingram commented
> These changes seem reasonable, do they enable the example in #1146 to work properly now?
> 
> If so can you create a test based on that example and add it to `test_asdf.py`?

Both examples, the local and http filesystems, should now work with tests for both (this PR adds the http filesystem support and tests). Let me know if there's anything else you'd like me to add to this PR otherwise it looks good to me.

2022-11-04 20:35 UTC, WilliamJamieson approved these changes

2022-11-04 20:35 UTC, merged