Add new plugin type for custom schema validators
asdf-format/asdf pull request #1328
Opened 2023-01-21 09:05 UTC by eslavich

This resurrects #1050 so that we can merge it to master and include in a 2.x release.

2023-01-22 12:11 UTC, CagtayFabry commented
I will try to run this against the previous test branch again soon @eslavich

2023-01-23 15:04 UTC, WilliamJamieson commented
@eslavich is it possible to break this into smaller chunks?

2023-01-23 15:48 UTC, braingram requested changes
Overall this looks great.

I made a few minor documentation suggestions, changed some imports to relative and highlighted one test coverage gap (because of the change in ndarray validator scope).

2023-01-23 15:48 UTC, braingram commented on asdf/core/_extensions.py
> +from asdf.extension import ManifestExtension
```suggestion
from ..extension import ManifestExtension
```

2023-01-23 15:48 UTC, braingram commented on asdf/core/_integration.py
> +from asdf.resource import JsonschemaResourceMapping
```suggestion
from ..resource import JsonschemaResourceMapping
```

2023-01-23 15:48 UTC, braingram commented on asdf/core/_validators/ndarray.py
> +from asdf.tags.core.ndarray import validate_datatype, validate_max_ndim, validate_ndim
```suggestion
from ...extension import Validator
from ...tags.core.ndarray import validate_datatype, validate_max_ndim, validate_ndim
```

2023-01-23 15:48 UTC, braingram commented on asdf/extension/_manager.py
> +from asdf.util import get_class_name, uri_match
```suggestion
from ..tagged import Tagged
from ..util import get_class_name, uri_match
```

2023-01-23 15:48 UTC, braingram commented on asdf/extension/_manager.py
> +        return False
We should add a test to cover these cases since the numpy validators no longer test them.

2023-01-23 15:48 UTC, braingram commented on asdf/extension/_manager.py
> +    Wraps a list of validators and indexes them by schema property.
```suggestion
    Wraps a list of custom validators and indexes them by schema property.
```

2023-01-23 15:48 UTC, braingram commented on asdf/extension/_manager.py
> +        Validate an ASDF tree node against a schema property.
```suggestion
        Validate an ASDF tree node against custom validators for a schema property.
```

2023-01-23 15:48 UTC, braingram commented on asdf/extension/_manager.py
> +            return self.validate(schema_property, schema_property_value, node, schema)
Jsonschema appears to cache validators. The closure here captures self (ValidationManager) which I think is only holding references to the custom validators. It's probably safe to leave this as is but if we're concerned about collection of these objects we might be able to convert self to a weakref. Are there references that might warrant this change?

2023-01-23 15:48 UTC, braingram commented on docs/asdf/extending/extensions.rst
> +
Should we link to the extending validators or other documentation here in case the reader wants to know more?

2023-01-23 15:48 UTC, braingram commented on docs/asdf/extending/extensions.rst
> +        pass
```suggestion
    class FooValidator(Validator):
        schema_property = "bar"
        tags = ["asdf://example.com/example-project/tags/foo-1.0.0"]
        
        def validate(self, value, node, schema):
            if value != "baz":
                yield ValidationError("bar is not baz for foo object")
```
Should we flush this out to a complete example or link to the other example in the docs?

2023-01-23 20:07 UTC, braingram commented on asdf/extension/_manager.py
> +        return False
I opened a PR on your branch that should add coverage to these lines:
https://github.com/eslavich/asdf/pull/3

2023-02-06 07:50 UTC, CagtayFabry commented
> @braingram I think I've addressed all of your comments. The weldx failures are due to them using the old-style validators in their new-style extension:
> 
> https://github.com/BAMWelDX/weldx/blob/master/weldx/asdf/extension.py#L62-L66

Would it help to remove the code you linked from the new style extension to see if the legacy implementation still works @eslavich ?

2023-02-06 09:47 UTC, CagtayFabry commented
I have removed the incompatible validators from the new style extension, can you run the weldx downstream test again @eslavich ?

2023-02-07 17:20 UTC, braingram approved these changes

2023-02-07 17:29 UTC, braingram commented on asdf/extension/_manager.py
> +            return self.validate(schema_property, schema_property_value, node, schema)
Excellent! CacheInfo is super useful. I ran the suit and logged CacheInfo for all the lru_cache uses I could find (except for the legacy stuff). Here's the output (run on your source branch for this PR):
```bash
INFO     root:conftest.py:25 _get_cached_extension_manager: CacheInfo(hits=1356, misses=365, maxsize=128, currsize=128)
INFO     root:conftest.py:25 _get_cached_validator_manager: CacheInfo(hits=379, misses=4, maxsize=128, currsize=4)
INFO     root:conftest.py:25 _create_validator: CacheInfo(hits=3100, misses=10, maxsize=128, currsize=10)
INFO     root:conftest.py:25 _load_schema: CacheInfo(hits=0, misses=0, maxsize=128, currsize=0)
INFO     root:conftest.py:25 load_custom_schema: CacheInfo(hits=0, misses=0, maxsize=128, currsize=0)
INFO     root:conftest.py:25 _load_schema_cached: CacheInfo(hits=0, misses=0, maxsize=128, currsize=0)
INFO     root:conftest.py:25 _compile_uri_match_pattern: CacheInfo(hits=15555414, misses=148, maxsize=1024, currsize=148)
```
I'm not sure if the number of misses for `_get_cached_extension_manager` is reasonable given that the tests fiddle with extensions but that's outside the scope of this PR. If it looks suspicious feel free to open an issue for it (or let me know and I can open one).

2023-02-07 17:29 UTC, braingram commented on docs/asdf/extending/extensions.rst
> +        pass
Thanks!

2023-02-09 20:14 UTC, braingram commented
> @eslavich is it possible to break this into smaller chunks?

@WilliamJamieson do you have a proposal for breaking this up or are you happy with it as is?

If you're happy with it I will rebase and merge this PR.

2023-02-13 15:58 UTC, merged