run jwst downstream tests in parallel
asdf-format/asdf pull request #1389
Opened 2023-02-17 20:38 UTC by braingram

testing speed of jwst tests run in parallel

2023-02-17 22:59 UTC, braingram commented
Comparing the run of the jwst downstream in this PR (run in parallel on 2 cores with pytest-xdist):
https://github.com/asdf-format/asdf/actions/runs/4207382736/jobs/7302102634
vs one in a recent PR (run serially):
https://github.com/asdf-format/asdf/actions/runs/4207209567/jobs/7301726071
Running the jwst tests in parallel (which jwst [appears to do](https://github.com/spacetelescope/jwst/blob/master/tox.ini#L4) with [similar performance](https://github.com/spacetelescope/jwst/actions/runs/4195427374/jobs/7274982870)) results in a roughly 1.5x speed up (28 vs 43 minutes).

@WilliamJamieson @zacharyburnett should we consider running at least jwst tests (and possibly other parts of the ci) in parallel?

If so, I'm happy to take this PR out of draft or replace (or have it replaced) by a more concerted effort.

2023-02-20 13:55 UTC, zacharyburnett commented
You can probably move this into a global tox factor by adding `pytest-xdist` to the `[testenv]` `deps` and also adding 
```
commands=
    pytest --remote-data \
    xdist: -n auto \
    {posargs}
```
Then we can run any of the toxenvs in parallel with `-xdist`

2023-02-20 14:49 UTC, zacharyburnett commented
> You can probably move this into a global tox factor in `[testenv]` by adding `pytest-xdist` to `deps` and also adding
> 
> ```diff
>   commands=
> -    pytest --remote-data
> +    pytest --remote-data \
> +    xdist: -n auto \
> +    {posargs}
> ```
> 
> Then we can run any of the toxenvs in parallel with `-xdist`

never mind, I didn't see that the `commands` are overridden; this should be fine for the downstream toxenvs, and then the global one can be another PR

2023-02-20 18:19 UTC, braingram commented
closing this, superceded by: #1396

2023-02-20 18:39 UTC, WilliamJamieson commented
> closing this, superceded by: #1396

#1396 does not superseed this PR, as it does not parallelize the JWST job.

2023-02-20 18:42 UTC, WilliamJamieson requested changes
Why not add the parallelization to all the downstream jobs?

2023-02-20 18:42 UTC, WilliamJamieson commented on tox.ini
> +    pytest -n auto jwst
```suggestion
    pytest --numprocesses auto jwst
```

2023-02-20 22:45 UTC, WilliamJamieson approved these changes

2023-02-21 17:15 UTC, merged